### ISSUE TITLE
[Feature request] Server Profiles

### ISSUE THREAD

**Issue by ema07cqc** [halpz/HalpoPlayer#12]
This project is awesome. I’m using the app daily. Loving it! Super fast, super clean and it just works. 

It would be awesome and unique to add the possibility to choose from different servers. I think it would be simply to save credentials of several servers and be able to choose any of them. The last server used should remain connected when the app relaunches. This would include an alias (Name) for each server.

I hope it's not so difficult to accomplish!

thanks! 

one more thing: add a button to give some donations ;)

**Comment by halpz** [comment]
good idea!

**Comment by halpz** [comment]
it's now implemented in the latest version

**Comment by ema07cqc** [comment]
awesome! thanks! hoping to get the new version soon.
