### ISSUE TITLE
[Feature request] Report playback to server

### ISSUE THREAD

**Issue by el-tiuri** [halpz/HalpoPlayer#13]
It’d be nice if the app reported the playback to the server. This way it would be reflected in playback statistics on the server’s end (like recently played or frequently played), and it’d enable the music to be scrobbled to last.fm.

It’d be especially nice if music played when not connected to the server would be reported when reconnected to the server.

**Comment by halpz** [comment]
Thanks for letting me know - I have implemented scrobbling now - it should be included in the live app soon

**Comment by ema07cqc** [comment]
Hey @el-tiuri is it working for you? When I play anything on the Navidrome web client every song is reported correctly to Last.fm. But when I play any song in HalpoPlayer iOS app (1.0.7) it doesn’t. Is there any setting I am missing?
