### ISSUE TITLE
Question: Minimum iOS version requirement

### ISSUE THREAD

**Issue by Spappz** [halpz/HalpoPlayer#4]
HalpoPlayer apparently requires at least iOS 16.0. Out of curiosity, what's the reason for this? If it's one specific 'optional' feature, would it be possible to bundle the app without that feature to remove that requirement?

I'm currently stuck on iOS 15.x due to me using an older iPhone model but your work looks very cool. I'm coming from a position of zero knowledge of iOS development; no worries at all if it's simply infeasible and I should keep up with the times!

**Comment by halpz** [comment]
I could make it compatible with earlier versions but currently the app uses [NavigationPath](https://developer.apple.com/documentation/swiftui/navigationpath) and [SearchScopes](https://developer.apple.com/documentation/swiftui/view/searchscopes(_:scopes:)?language=objc).

the search scopes would be easy to replace, but the navigation one is an architectural choice for the app's navigation - I will see if there is a suitable replacement I could use

**Comment by Spappz** [comment]
Good to know. If it's that hard-baked then I wouldn't even want you to add to your workload just for 2016-era technology 🤣

Apple likes deprecating anything more than 5 years old; part of the deal with the devil you make with them I guess. I'll be picking up a new device sometime soon anyway (other software slowly leaving me in the dust) so I look forward to trying Halpo out then. Thanks!

(I'll let you close the issue when you're comfortable)
