### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by PauFCB** [halpz/HalpoPlayer#5]
Hi! Thank you for develop this app, as Im looking to a native and modern iOs Navidrome app. I have a few suggestions:
1. Blur background colors for the player screen.
2. Clickable artists with bio and poster
3. Grid view for album
4. Make the player controls without color shapes like the Apple Music app and maybe a volume slider.
Thanks!

**Comment by halpz** [comment]
Thanks for the suggestions

1. for this I am thinking of making a new now playing screen that is full screen when you tap on the playing bar
2. I have implemented this in the next version
3. Grid view is available for iPad, I will probably also make it an option on iPhone in the future
4. I will redesign this with the new now playing bar!
